version: '3'
services:
  backend:
    build: .
    ports:
      - 5000:5000
  frontend:
    volumes:
        - ./frontend:/usr/src/app/frontend
    working_dir: /usr/src/app/frontend
    build: ./frontend
    ports:
      - 3000:3000
    depends_on:
      - backend
